version: '3.8'

services:
  api:
    environment:
      - DEBUG=true
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS,PATCH
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization,X-Requested-With,X-Request-ID
      - CORS_ALLOW_CREDENTIALS=true
    command: >
      sh -c "
        echo 'Building application with debug symbols...' &&
        go build -gcflags='-N -l' -o ./tmp/main ./cmd/api &&
        echo 'Starting debugger on :2345...' &&
        dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient --continue --log --check-go-version=false exec ./tmp/main
      "